// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	core_feed "toy-tok/biz/router/core_feed"
	core_publish "toy-tok/biz/router/core_publish"
	core_user "toy-tok/biz/router/core_user"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	core_user.Register(r)

	core_publish.Register(r)

	core_feed.Register(r)
}
